### ISSUE TITLE
pathfinder sync failed

### ISSUE THREAD

**Issue by wangjiangw** [eqlabs/pathfinder#2672]
![Image](https://github.com/user-attachments/assets/44e94c99-25e5-441f-9c52-96bcb5e43ce3)

**Comment by kkovaacs** [comment]
Which version of Pathfinder are you running? And which chain are you trying to sync?

Starknet Mainnet is just being upgraded to Starknet 0.13.5, which requires Pathfinder 0.16.2 to sync.

**Comment by wangjiangw** [comment]
@kkovaacs we are using 0.16.2

**Comment by wangjiangw** [comment]
yes, the starknet mainnet sync slowly after block 1256129, and the pathfinder will produce 

![Image](https://github.com/user-attachments/assets/d7e364c8-f109-46b6-a0d7-d9ca0f350754)

**Comment by wangjiangw** [comment]
after increase the timeout, the sync process will failed

**Comment by kkovaacs** [comment]
Looks like there's an ongoing issue with the feeder gateway API on Starknet mainnet that is currently being fixed by Starkware.

**Comment by kkovaacs** [comment]
According to Starkware, the feeder gateway issue should be fixed now. Can you please check again?

**Comment by wangjiangw** [comment]
It looks haven't been fixed, the error still exists.

![Image](https://github.com/user-attachments/assets/465f2b3a-23bc-4d3d-a373-14cf13d017a2)

**Comment by kkovaacs** [comment]
Apparently, the Starknet 0.13.5 was still going on around the time you've seen the failure. Has your node recovered since then?

**Comment by wangjiangw** [comment]
@kkovaacs no, I have to rebuild the node by copying another node's data.

**Comment by wangjiangw** [comment]
![Image](https://github.com/user-attachments/assets/d0005676-a203-4378-85f2-36a5a9e22055) @kkovaacs

**Comment by kkovaacs** [comment]
OK, thanks.

All issues should be solved by now on Starknet mainnet.
